/**
 * World config — Irish 5G (646 cells) — generated by world-builder agent
 * DO NOT EDIT
 */
'use strict';
const path = require('path');
const FAST_MODE = process.env.FAST_MODE === '1';
const FAST_MULT = 10;
module.exports = {
  WORLD_STATE_FILE: path.join(__dirname, '..', 'world-state.json'),
  TICK_INTERVAL_MS: FAST_MODE ? 30_000 : 5 * 60_000,
  SPAWN_PROBABILITY: {
    equipment_fault: FAST_MODE ? 0.0038 * FAST_MULT : 0.0038,
    interference:    FAST_MODE ? 0.003 * FAST_MULT : 0.003,
    backhaul_fault:  FAST_MODE ? 0.0025 * FAST_MULT : 0.0025,
    maintenance:     FAST_MODE ? 0.002 * FAST_MULT : 0.002,
  },
  EVENT_DURATION_MINUTES: {
    equipment_fault: [120, 480], interference: [180, 720],
    backhaul_fault:  [30,  240], maintenance:  [20,   60],
  },
  MAX_CONCURRENT: {
    equipment_fault: 10,
    interference:    5,
    backhaul_fault:  5,
    maintenance:     10,
  },
  GHOST_ALARM_PROBABILITY: 0.25,
  GHOST_ALARM_DURATION_MINUTES: [30, 120],
  REQUEST_NOISE: 0.04,
  EVENT_EFFECTS: {
    equipment_fault: { dlThpCell: { mode: 'scale', value: 0.12 }, ulThpCell: { mode: 'scale', value: 0.15 },
      errorRate: { mode: 'set', value: 14.7 }, cellAvailTime: { mode: 'set', value: 91.2 },
      pmRrcConnEstabSucc: { mode: 'set', value: 10 } },
    interference: { dlThpCell: { mode: 'scale', value: 0.75 }, ulThpCell: { mode: 'scale', value: 0.80 },
      errorRate: { mode: 'add', value: 2.5 }, cellAvailTime: { mode: 'set', value: 98.5 } },
    backhaul_fault: { dlThpCell: { mode: 'scale', value: 0.25 }, ulThpCell: { mode: 'scale', value: 0.30 },
      errorRate: { mode: 'set', value: 8.0 }, cellAvailTime: { mode: 'set', value: 85.0 },
      pmRrcConnEstabSucc: { mode: 'scale', value: 0.20 } },
    maintenance: { dlThpCell: { mode: 'set', value: 0 }, ulThpCell: { mode: 'set', value: 0 },
      errorRate: { mode: 'set', value: 0 }, cellAvailTime: { mode: 'set', value: 0 },
      pmRrcConnEstabSucc: { mode: 'set', value: 0 }, pmRrcConnEstabAtt: { mode: 'set', value: 0 } },
  },
};
