/**
 * Shared network builder — used by build-ireland.js (initial generation)
 * and growth-agent.js (incremental expansion).
 *
 * Exports: buildNetwork(design), genDataFile(SITES, CELLS), genConfigFile(design, totalCells), writeAll(design)
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const OUT_DATA   = path.join(ROOT, 'data-ireland.js');
const OUT_CONFIG = path.join(ROOT, 'world', 'config-ireland.js');

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

const LAT_KM = 111.0;
const lonKm  = lat => 111.0 * Math.cos(lat * Math.PI / 180);

function sitesInCircle(lat, lon, radius_km, n) {
  const rlat  = radius_km / LAT_KM;
  const rlon  = radius_km / lonKm(lat);
  const gridN = Math.ceil(Math.sqrt(n * 1.8)) + 2;
  const slat  = (2 * rlat) / gridN;
  const slon  = (2 * rlon) / gridN;
  const pts   = [];
  for (let i = 0; i < gridN; i++) {
    for (let j = 0; j < gridN; j++) {
      const plat = lat - rlat + i * slat + (Math.random() - 0.5) * slat * 0.7;
      const plon = lon - rlon + j * slon + (Math.random() - 0.5) * slon * 0.7;
      const dkm  = Math.sqrt(((plat - lat) * LAT_KM) ** 2 + ((plon - lon) * lonKm(lat)) ** 2);
      if (dkm <= radius_km) pts.push({ lat: +plat.toFixed(5), lon: +plon.toFixed(5) });
    }
  }
  pts.sort(() => Math.random() - 0.5);
  return pts.slice(0, n);
}

function sitesAlongRoad(waypoints, spacing_km) {
  const pts = [];
  for (let i = 0; i < waypoints.length - 1; i++) {
    const [la1, lo1] = waypoints[i], [la2, lo2] = waypoints[i + 1];
    const segKm = Math.sqrt(((la2-la1)*LAT_KM)**2 + ((lo2-lo1)*lonKm(la1))**2);
    const steps = Math.max(1, Math.round(segKm / spacing_km));
    for (let s = 0; s < steps; s++) {
      const t = s / steps;
      pts.push({ lat: +(la1+(la2-la1)*t).toFixed(5), lon: +(lo1+(lo2-lo1)*t).toFixed(5) });
    }
  }
  return pts;
}

// ---------------------------------------------------------------------------
// Build SITES + CELLS arrays from a design object
// ---------------------------------------------------------------------------

function buildNetwork(design) {
  const CPZ = design.cells_per_site || { urban: 6, suburban: 4, rural: 3, motorway: 3 };
  const sites = [];

  for (const z of (design.zones || [])) {
    const pos = sitesInCircle(z.lat, z.lon, z.radius_km, z.site_count);
    for (let i = 0; i < pos.length; i++)
      sites.push({ id: `${z.name}-${String(i+1).padStart(3,'0')}`, ...pos[i], zone: z.type });
  }

  for (const r of (design.roads || [])) {
    const pos = sitesAlongRoad(r.waypoints, r.site_spacing_km || 2.5);
    for (let i = 0; i < pos.length; i++)
      sites.push({ id: `${r.name}-${String(i+1).padStart(3,'0')}`, ...pos[i], zone: 'motorway' });
  }

  const CELLS = [];
  let cellId = 1, pciBase = 0;
  for (let si = 0; si < sites.length; si++) {
    const count = CPZ[sites[si].zone] || 3;
    const tac   = 100 + (si % 900);
    for (let c = 0; c < count; c++) CELLS.push([si, cellId++, (pciBase + c) % 1008, tac]);
    pciBase = (pciBase + count + 3) % 1008;
  }

  return { SITES: sites, CELLS };
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function genDataFile(SITES, CELLS, model) {
  const now  = new Date().toISOString();
  const date = now.slice(0, 10);
  const credit = model ? `generated by ${model} world-builder agent` : 'generated by network-builder';
  return `/**
 * Irish 5G network — ${credit}
 * Sites: ${SITES.length} | Cells: ${CELLS.length} | Generated: ${now}
 * DO NOT EDIT — re-run build-ireland.js to regenerate
 */
'use strict';

const BASE_DN = 'SubNetwork=Ireland,MeContext={site},ManagedElement=1,GNBDUFunction=1';
const SITES = ${JSON.stringify(SITES, null, 2)};
// [siteIdx, localId, nRPCI, nRTAC]
const CELLS = ${JSON.stringify(CELLS)};

function cellUrn(siteId, localId) {
  return \`urn:3gpp:dn:\${BASE_DN.replace('{site}', siteId)},NRCellDU=\${localId}\`;
}
function sectorUrn(siteId, localId) {
  return \`urn:3gpp:dn:\${BASE_DN.replace('{site}', siteId)},NRSectorCarrier=\${localId}\`;
}
function buildCells() {
  return CELLS.map(([si, localId]) => ({
    id: cellUrn(SITES[si].id, localId), site: SITES[si].id,
    localId, zone: SITES[si].zone, lat: SITES[si].lat, lon: SITES[si].lon,
  }));
}
function buildTopology() {
  const cells = [], relationships = [];
  for (const [si, localId, nrpci, nrtac] of CELLS) {
    const site = SITES[si], urn = cellUrn(site.id, localId);
    cells.push({
      id: urn,
      attributes: { cellLocalId: localId, nCI: 10000 + localId, nRPCI: nrpci, nRTAC: nrtac },
      decorators: { site: site.id, lat: site.lat, lon: site.lon, zone: site.zone },
      classifiers: [], sourceIds: [urn],
      metadata: { reliabilityIndicator: 'OK', firstDiscovered: '2025-06-01T00:00:00Z', lastModified: '${date}T00:00:00Z' },
    });
    relationships.push({
      id: \`urn:rel:NRCELLDU_USES_NRSECTORCARRIER:\${localId}\`,
      aSide: urn, bSide: sectorUrn(site.id, localId),
      metadata: { reliabilityIndicator: 'OK', firstDiscovered: '2025-06-01T00:00:00Z', lastModified: '${date}T00:00:00Z' },
    });
  }
  return {
    cells: { items: cells.map(c => ({ 'o-ran-smo-teiv-ran:NRCellDU': [c] })), totalCount: cells.length,
      _links: { self: { href: '/topology-inventory/v1/domains/RAN/entity-types/NRCellDU/entities' } } },
    relationships: { items: relationships.map(r => ({ 'o-ran-smo-teiv-ran:NRCELLDU_USES_NRSECTORCARRIER': [r] })), totalCount: relationships.length,
      _links: { self: { href: '/topology-inventory/v1/domains/RAN/relationship-types/NRCELLDU_USES_NRSECTORCARRIER/relationships' } } },
  };
}
const topology = buildTopology();
const cells    = buildCells();
module.exports = { topology, cells, SITES, CELLS, cellUrn, sectorUrn };
`;
}

function genConfigFile(design, totalCells) {
  const ep  = design.event_probabilities || {};
  const avg = key => {
    const vals = ['urban','suburban','rural','motorway'].map(z => ep[z]?.[key] || 0).filter(Boolean);
    return vals.length ? +(vals.reduce((a,b) => a+b,0) / vals.length).toFixed(4) : 0;
  };
  const eqf = avg('equipment_fault') || 0.0038;
  const int = avg('interference')    || 0.003;
  const bkh = avg('backhaul_fault')  || 0.0025;
  const mnt = avg('maintenance')     || 0.002;
  return `/**
 * World config — Irish 5G (${totalCells} cells) — generated by world-builder agent
 * DO NOT EDIT
 */
'use strict';
const path = require('path');
const FAST_MODE = process.env.FAST_MODE === '1';
const FAST_MULT = 10;
module.exports = {
  WORLD_STATE_FILE: path.join(__dirname, '..', 'world-state.json'),
  TICK_INTERVAL_MS: FAST_MODE ? 30_000 : 5 * 60_000,
  SPAWN_PROBABILITY: {
    equipment_fault: FAST_MODE ? ${eqf} * FAST_MULT : ${eqf},
    interference:    FAST_MODE ? ${int} * FAST_MULT : ${int},
    backhaul_fault:  FAST_MODE ? ${bkh} * FAST_MULT : ${bkh},
    maintenance:     FAST_MODE ? ${mnt} * FAST_MULT : ${mnt},
  },
  EVENT_DURATION_MINUTES: {
    equipment_fault: [120, 480], interference: [180, 720],
    backhaul_fault:  [30,  240], maintenance:  [20,   60],
  },
  MAX_CONCURRENT: {
    equipment_fault: ${Math.max(10, Math.round(totalCells * 0.010))},
    interference:    ${Math.max(5,  Math.round(totalCells * 0.005))},
    backhaul_fault:  ${Math.max(5,  Math.round(totalCells * 0.005))},
    maintenance:     ${Math.max(10, Math.round(totalCells * 0.008))},
  },
  GHOST_ALARM_PROBABILITY: 0.25,
  GHOST_ALARM_DURATION_MINUTES: [30, 120],
  REQUEST_NOISE: 0.04,
  EVENT_EFFECTS: {
    equipment_fault: { dlThpCell: { mode: 'scale', value: 0.12 }, ulThpCell: { mode: 'scale', value: 0.15 },
      errorRate: { mode: 'set', value: 14.7 }, cellAvailTime: { mode: 'set', value: 91.2 },
      pmRrcConnEstabSucc: { mode: 'set', value: 10 } },
    interference: { dlThpCell: { mode: 'scale', value: 0.75 }, ulThpCell: { mode: 'scale', value: 0.80 },
      errorRate: { mode: 'add', value: 2.5 }, cellAvailTime: { mode: 'set', value: 98.5 } },
    backhaul_fault: { dlThpCell: { mode: 'scale', value: 0.25 }, ulThpCell: { mode: 'scale', value: 0.30 },
      errorRate: { mode: 'set', value: 8.0 }, cellAvailTime: { mode: 'set', value: 85.0 },
      pmRrcConnEstabSucc: { mode: 'scale', value: 0.20 } },
    maintenance: { dlThpCell: { mode: 'set', value: 0 }, ulThpCell: { mode: 'set', value: 0 },
      errorRate: { mode: 'set', value: 0 }, cellAvailTime: { mode: 'set', value: 0 },
      pmRrcConnEstabSucc: { mode: 'set', value: 0 }, pmRrcConnEstabAtt: { mode: 'set', value: 0 } },
  },
};
`;
}

function writeAll(design, SITES, CELLS, model) {
  fs.writeFileSync(OUT_DATA,   genDataFile(SITES, CELLS, model));
  fs.writeFileSync(OUT_CONFIG, genConfigFile(design, CELLS.length));
}

module.exports = { buildNetwork, genDataFile, genConfigFile, writeAll };
